package com.flowops.auth.domain.enums;

public enum AuthAction {
    SIGNUP_PASSCODE_ISSUED,
    DUPLICATE_SIGNUP_ATTEMPT,
    SIGNUP_COMPLETED,
    SIGNUP_FAILED,

    INVITED_ACCOUNT_CREATED,

    WORKSPACE_CREATION_REQUESTED,

    SETUP_COMPLETED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    LOGGED_OUT,
    REAUTHENTICATION_SUCCEEDED,
    REAUTHENTICATION_FAILED,
    PASSWORD_CHANGED,

    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_RESET_REFUSED,

    SESSIONS_OF_PERSON_LISTED,

    SESSION_TERMINATED,

    SESSION_TERMINATION_ATTEMPTED,

    SESSION_TERMINATION_DENIED,

    SESSION_VIEW_DENIED
}
