package com.flowops.process.domain.enums;

public enum ProcessAction {
    TEMPLATE_AUTHORED,
    TEMPLATE_EDITED,
    DEPENDENCY_DEFINED,
    DEPENDENCY_REMOVED,
    INSTANCE_STARTED,
    STEP_REACHED,
    STEP_ASSIGNED,
    STEP_RETURNED_FOR_REASSIGNMENT,

    STEP_SKIPPED,

    STEP_CLOSED,
    INSTANCE_COMPLETED,

    TASK_ADDED_TO_INSTANCE,

    TASK_REMOVED_FROM_INSTANCE,

    INSTANCE_TASKS_REORDERED,

    TEMPLATE_RETIRED,

    INSTANCE_ABANDONED,

    INSTANCE_ARCHIVED,

    INSTANCE_RESTORED
}
